# Generated by Django 5.2.5 on 2025-10-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_booking_source'),
    ]

    operations = [
    ]
