# Generated by Django 5.2.5 on 2025-10-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_auto_20251029_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
