# Generated by Django 5.2.5 on 2025-10-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_departure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
